### PR TITLE
Create integrations with predefined token

### PR DESCRIPTION
**Pull request by StrDragos**
[VTX-2151]

[VTX-2151]: https://coralogix.atlassian.net/browse/VTX-2151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by stsatlantis** [comment]
Why don't we just extend the existing one with `token` field? So it either needs to generate it or just take the token as it as

**Comment by StrDragos** [comment]
> Why don't we just extend the existing one with `token` field? So it either needs to generate it or just take the token as it as

I thought this is cleaner than just adding a token field. But sure it can be done like that.

**Comment by rtimush** [comment]
I think adding an optional token field is quite reasonable and it is easier to maintain than a completely separate API call.

**Review by rtimush — APPROVED** [review]

**Comment by rtimush** [comment]
`.idea/workspace.xml` shouldn't be in this PR though.

**Comment by stsatlantis** [comment]
> `.idea/workspace.xml` shouldn't be in this PR though.

@StrDragos ^ valid point

**Pull request merged**
