### PR TITLE
added okta enum

### PR DESCRIPTION
**Pull request by kolov**

### CODE REVIEW

**Review by zagyi — DISMISSED** [review]

**Review by zhrebicek — DISMISSED** [review]
Minor, but I guess you can add `CODEOWNERS` from some other repo so we have automatic reviewers.

**Comment by zhrebicek** [comment]
Also it is missing meta.yaml and whatnot so as you wish merge it as it but we should add it later.

**Comment by kolov** [comment]
> Also it is missing meta.yaml and whatnot so as you wish merge it as it but we should add it later.

What should be in the meta.yaml of a repo with proto files only? Here's another one: https://github.com/coralogix/cx-api-integrations

**Comment by kolov** [comment]
@zhrebicek Can you hit approve again pls

**Review by zhrebicek — APPROVED** [review]

**Pull request merged**
